package:
  name: dummy-basic
  version: "0.1.6"

source:
  git_url: https://github.com/chimmy-changa/dummy-basic.git #
  git_rev: "v0.1.6"

build:
  number: 0
  noarch: python
  skip: true # [not linux]
  entry_points:
    - get_hello = dummy_basic.get:print_hello
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - aiohttp >=3.7.4
    - jupyter-server-proxy
    - python >=3.7

test:
  commands:
    - get_hello --help

  requires:
    - psutil
    - pytest
    - pytest-runner
    - pytest-aiohttp
    - pytest-cov
    - pytest-env
    - pytest-mock
    - requests

  # imports:
  #   - dummy_basic
  #   - dummy_basic.get_hello

about:
  home: "https://github.com/chimmy-change/dummy-basic"
  license: Generic
  license_family: OTHER
  license_file: LICENSE.md
  summary: "Gets strings"
  doc_url: "https://github.com/chimmy-changa/dummy-basic"
  dev_url: "https://github.com/chimmy-changa/dummy-basic"

  extra:
  recipe-maintainers:
    - chimmy-changa
